// Database barrel exports - CRUD only (no business logic)
export * from './activities/vineyardDB';
export * from './activities/inventoryDB';
export * from './core/gamestateDB';
export * from './core/staffDB';
export * from './core/highscoresDB';
export * from './core/companiesDB';
export * from './core/usersDB';
export * from './core/transactionsDB';
export * from './core/wineLogDB';
export * from './core/lendersDB';
export * from './core/loansDB';
export * from './customers/customerDB';
export * from './customers/relationshipBoostsDB';
export * from './core/researchUnlocksDB';
export * from './sales/grapeBuyerMarketDB';
export * from './sales/grapeSupplierMarketDB';
export * from './sales/grapeBuyerLoyaltyDB';
export * from './sales/grapeSupplierLoyaltyDB';
export * from './sales/cooperativeDB';
export * from './market/buyMarketOffersDB';
export * from './market/grapeMarketOffersDB';
export * from './market/buyMarketCounterpartyRelationshipsDB';
export * from './market/storageVesselMarketListingsDB';
export * from './winery/storageVesselsDB';
export { supabase } from './core/supabase';
